### PR TITLE
[enhancement] Do `sudo apt-get update` beforehand

### PR DESCRIPTION
**Pull request by GabrielBB**
Please see: https://github.com/GabrielBB/xvfb-action/issues/24#issuecomment-1477672587

### CODE REVIEW

**Review by haydncomley — COMMENTED** [review]
**suggestion:** Could these be split into two separate `async/try-catch` blocks in order to report better failings to the end user?

**Comment by GabrielBB** [comment]
> **suggestion:** Could these be split into two separate `async/try-catch` blocks in order to report better failings to the end user?

@haydncomley Feel free to open that PR and I close this one

**Comment by GabrielBB** [comment]
> **suggestion:** Could these be split into two separate `async/try-catch` blocks in order to report better failings to the end user?

Okay

**Review by haydncomley — APPROVED** [review]
🎉

**Comment by gselzer** [comment]
Hi @GabrielBB @haydncomley @ssbarnea, I'm getting bitten by this, is there anything blocking merge here?

**Comment by haydncomley** [comment]
> Hi @GabrielBB @haydncomley @ssbarnea, I'm getting bitten by this, is there anything blocking merge here?

I've approved the changes a while ago but I'm not a maintainer so can't do much with this unfortunately..

**Comment by GabrielBB** [comment]
> Hi @GabrielBB @haydncomley @ssbarnea, I'm getting bitten by this, is there anything blocking merge here?

@ssbarnea is code owner :/ He needs to approve/merge

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
Thanks for mentioning me. BTW, if someone wants to help with maintenance say it and I will invite you to the repo.

**Pull request merged**
